// Code generated by MockGen. DO NOT EDIT.
// Source: nutrition_facts.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/nutrition_facts.go -package=mocks -source=nutrition_facts.go
//
// Package mocks is a generated GoMock package.
package mocks
