// Code generated by MockGen. DO NOT EDIT.
// Source: recipe.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/recipe.go -package=mocks -source=recipe.go
//
// Package mocks is a generated GoMock package.
package mocks
